# Streamlit Cloud secrets configuration
# This file should NOT be committed to version control

[database]
# Database connection strings (if using external DB)
# connection_string = "your_database_connection_string"

[api_keys]
# External API keys for data sources
# fca_api_key = "your_fca_api_key"
# companies_house_key = "your_companies_house_key"

[monitoring]
# Monitoring and alerting configuration
# slack_webhook = "your_slack_webhook_url"
# email_smtp_server = "smtp.gmail.com"
# email_username = "your_email@gmail.com"
# email_password = "your_app_password"

[github]
# GitHub token for automated updates
# github_token = "your_github_token"