[global]
# Streamlit global configuration settings
developmentMode = false
showWarningOnDirectExecution = false

[server]
# Server configuration for deployment
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false

[browser]
# Browser-specific settings
gatherUsageStats = false
showErrorDetails = false

[theme]
# Custom theme for fintech professional look
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[logger]
# Logging configuration
level = "info"
messageFormat = "%(asctime)s %(name)s %(levelname)s: %(message)s"

[client]
# Client-side settings
caching = true
displayEnabled = true
showErrorDetails = false

[runner]
# Application runner settings
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = true
enforceSerializableSessionState = false